server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/smarthire?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Sujit@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never
spring.web.resources.static-locations=file:./SmartHire_web/
